name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight
  workflow_dispatch:       # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate LeetCode Card
        uses: JasonEtco/rss-to-readme@v1
        with:
          url: https://leetcard.jacoblin.cool/Ashutoshanand2287?ext=heatmap
          file: README.md
